### ISSUE TITLE
PSVR thoughts

### ISSUE THREAD

**Issue by MaVe-64** [cboulay/PSMoveService#247] opened 2016-10-16 06:58 UTC
What are you guys thoughts on the psvr? I'm eagerly waiting for the moment it's hacked to the PC. 
Will you be implementing it for roomscale tracking, and even better, motion sensor tracking? 
If so, I think the hardest work to get it working on PC is done. That would be so great!

**Comment by HipsterSloth** [comment] 2016-10-16 07:02
For discussion questions like this one we usually prefer to have them on the google groups page since we are trying to make the issues list purely about reproducible bugs.

I copied your question to a new thread there: 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/psmoveservice/vXe5DXQDGHQ

I'll respond to it over there.

Closing this issue for tracking purposes

**Closed by HipsterSloth** 2016-10-16 07:02 UTC

**Comment by HipsterSloth** [comment] 2016-10-16 07:51
Reply posted here: https://groups.google.com/d/msg/psmoveservice/vXe5DXQDGHQ/Mon7-2DxBAAJ
