### ISSUE TITLE
Ps Move Controller disconnecting.

### ISSUE THREAD

**Issue by monsterjj00** [cboulay/PSMoveService#331] opened 2017-01-12 11:59 UTC
The controller pairs fine and charges fine, but when I do anything like testing the controller/tracking or play something through steam VR for more than 3 or 4 minutes it just disconnects and turns off.

Heres what the log says.
#
[2017-01-12 03:40:52.789]: main - Starting PSMoveService v0.9-alpha 6.0.9
[2017-01-12 03:40:52.808]: bluetooth_get_host_address - Found a bluetooth radio
[2017-01-12 03:40:52.813]: bluetooth_get_host_address - Retrieved radio info
[2017-01-12 03:40:52.898]: PS3EyeTracker::open - Opening PS3EyeTracker(USB\VID_1415&PID_2000\11\0, camera_index=0)
[2017-01-12 03:40:53.153]: SharedMemory::initialize() - Allocating shared memory: tracker_view_0
[2017-01-12 03:40:53.492]: DeviceTypeManager::update_connected_devices - Device device_id 0 (PSEYE) opened
[2017-01-12 03:40:53.499]: PS3EyeTracker::open - Opening PS3EyeTracker(USB\VID_1415&PID_2000\23\1, camera_index=1)
[2017-01-12 03:40:53.751]: SharedMemory::initialize() - Allocating shared memory: tracker_view_1
[2017-01-12 03:40:53.771]: DeviceTypeManager::update_connected_devices - Device device_id 1 (PSEYE) opened
[2017-01-12 03:41:08.13]: PSMoveController::open - Opening PSMoveController(\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&03d5&col01#8&2c9e94e7&f&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})
[2017-01-12 03:41:08.27]: PSMoveController::open -   with serial_number: 0006f7d0b4b6
[2017-01-12 03:41:08.184]: DeviceTypeManager::update_connected_devices - Device device_id 0 (PSMove) opened
[2017-01-12 03:41:27.166]: ClientConnection::start - Starting client connection id 0
[2017-01-12 03:41:27.171]: ClientConnection::send_connection_info - Sending connection id to client 0
[2017-01-12 03:41:27.220]: ServerRequestHandler - Start controller(0) stream (pos=1,phys=1,raw_sens=0,cal_sens=0,trkr=0,roi=0)
[2017-01-12 03:42:05.412]: PSMoveController::readDataIn - HID ERROR: The device is not connected.
[2017-01-12 03:42:05.420]: ServerDeviceView::poll - Device id 0 closing due to failed read
[2017-01-12 03:42:05.426]: PSMoveController::close - Closing PSMoveController(\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&03d5&col01#8&2c9e94e7&f&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})

**Comment by HipsterSloth** [comment] 2017-01-12 18:06
The "Device id 0 closing due to failed read" error for controller means that the USB bandwidth is probably getting saturated on that root hub. You likely have your USB bluetooth adapter on the same USB root hub as you PS3EYECameras. You can tell which devices are connected to which root hub either by using the windows device manager or using the "USBView" tool found here: http://k0lee.com/dc3000/usbts.htm

![roothubs](https://cloud.githubusercontent.com/assets/16793853/21901919/b559833a-d8ae-11e6-8173-9d2e44310c3e.jpg)

If this is in fact the case for you, try moving the bluetooth adapter to a different USB port and then see if that puts it under a different root hub.

Also for future reference, please post troubleshooting questions to the google group first.: 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/psmoveservice
Once we determine that the issue is in fact a code problem, we'll make a new issue for it here.

**Closed by HipsterSloth** 2017-01-12 18:06 UTC
