### ISSUE TITLE
Add hot-key in SteamVR to reset the HMD tracking space alignment (yaw+position)

### ISSUE THREAD

**Issue by xMindweaverx** [cboulay/PSMoveService#123] opened 2016-07-18 19:50 UTC
I think this has been discussed before, but I can't find it in the "_open_" or "_closed_" issues. I've noticed over time everything slowly goes out of tracking. _Example: If in front of me is 0 degrees then by the time I get to the 3rd round/song in Audioshield then everything is facing around 90 degrees in the same session._ Then I have to redo The Calibration Mat. Can I do anything to improve this?

I plan tonight to stop and get a better led light for my Computer Room/VR space. I'm hope to go from a 60watt to 120watt. Maybe put it on a dimmer and adjust to the best lighting. Thanks guys for your hard work! 

Oh and my wife finally was able to enjoy a VR game with out getting sick playing Audioshield! I now might be getting a Vive sooner than later.

**Comment by cboulay** [comment] 2016-07-18 20:03
What you describe is 'yaw drift'.

If the entire world is rotating, then you're getting yaw drift in your head and there's nothing we can do about that (unless a PSMove-on-head is your head-tracking method).
If the controllers are rotating but the world is stationary then there is something we can do about that.

**Comment by cboulay** [comment] 2016-07-18 20:07
Actually, maybe there is something we can do about it. Maybe we can provide a hot-key that will reset the yaw=0 direction of the entire hmd-to-psmove transform to whatever the currently faced direction is. Your game world will still rotate around slowly, so you'll have to turn your head/body to follow the game's new 'forward', but at least you can bring the controllers with you.

Really the better solution is to reset yaw within your head-tracking solution.

**Comment by HipsterSloth** [comment] 2016-07-18 20:29
@cboulay I've actually been debating about moving the HMD alignment out of calibration mat tool and putting that inside the steamvr plugin instead. The alignment would be done by holding the controller in front of your face and pressing some button combination for a few seconds. The razer hydra steam vr plugin does something similar.

@xMindweaverx You mentioned earlier you were using VRidge? Do they expose any recenter option in their settings?

**Comment by zelmon64** [comment] 2016-07-18 21:53
@xMindweaverx That is certainly yaw drift on your phone. Try switching to a different tracking mode (the responsive one is usually good). VRidge yaw can be recentered with ctrl+shift+alt+R (this hotkey can be changed in the settings). It is also possible to recalibrate the magnetometer on some phones which could help.

**Comment by xMindweaverx** [comment] 2016-07-18 23:03
@cboulay yea the whole world is rotating, and the cameras and controllers.

@HipsterSloth a reset button would be great.

HipsterSloth and @zelmon64 I'm using a Oculus Rift DK1. I've used VRidge before but I prefer my DK1 over VRidge+Phone due to lag and resolution.

**Comment by HipsterSloth** [comment] 2016-07-18 23:59
@xMindweaverx You might try re calibrating the magnetometer for the DK1. It's been a while since I ran the 0.8 SDK (which I'm assuming you are running) but I believe they had a tool for calibrating the magnetometer for situations like this. I found a youtube video describing the calibration process here: https://www.youtube.com/watch?v=UusZSHOUB9M. To be honest I don't know if this video was made for an earlier SDK and they since removed that calibration tool or not.

**Comment by xMindweaverx** [comment] 2016-07-19 00:20
@HipsterSloth I re calibrated using 0.8 and reset center. Ran the Oculus demo and it looks good. I just redid the calibration and re did SteamVR Standing Calibration. What's the best way to rotate everything in the TrackerManagerConfig.json file? Thanks!

**Comment by HipsterSloth** [comment] 2016-07-19 00:45
@xMindweaverx The easiest way to rotate everything is just to run the calibration mat tool again. The last step where you place the HMD on the mat is used to fill in the orientation.

But if you would rather edit the config file to define the orientation you can, but it's going to be a little gross. As I mentioned in issue #113 the "orientation" in TrackerManagerConfig.json is a quaternion whose values can be interpreted as such:

* w=cos(angle/2)
* x=rotation_axis.x * sin(angle/2)
* y=rotation_axis.y * sin(angle/2)
* z=rotation_axis.z * sin(angle/2)

You always want to rotate about the y-axis so the the parameters will be like such:

* w=cos(angle/2)
* x=0
* y=sin(angle/2)
* z=0

So let's say you need to rotate your psmove tracking space 45 degrees. We can compute the values we need as follows (and forgive me if this is too explicit, I don't want these steps to sound patronizing, but I also don't want to assume any knowledge about trigonometry or windows calculator)

1. Open Windows calculator
2. Make sure you have "DEG" set for degrees
3. Type "45"
4. Divide by 2
5. Hit the "cos" button
6. Put the resulting value "0.923..." into "w" in TrackerManagerConfig.json
7. Hit "C" to clear
8. Type "45"
9. Divide by 2
10. Hit the "sin" button
11. Put the resulting value "0.382..." into "y" in TrackerManagerConfig.json

You're going to be rotating some other amount besides 45 degrees so you'd just replace 45 with the angle you want to rotate by.

I never originally intended people to be editing the TrackerManagerConfig.json manually like this so the process not user friendly. I'l probably change the orientation info to just be a yaw angle you can edit directly.

**Comment by xMindweaverx** [comment] 2016-07-19 01:31
@HipsterSloth You rock! Thanks buddy!

**Comment by xMindweaverx** [comment] 2016-07-19 15:52
I created a small config utility. [Here is the image](http://img.techpowerup.org/160719/ps-move-rotation-tool.jpg).

Here is the code I created to generate W and Y.
```

        {
            Double Degree = Convert.ToDouble(Num_Degree.Value);
            Double Angle = Math.PI * Degree / 180;
            Double WLine = Math.Cos((Angle) / 2);
            Double YLine = Math.Sin((Angle) / 2);

            Num_W.Value = Convert.ToDecimal(Math.Round(WLine, 9));
            Num_Y.Value = Convert.ToDecimal(Math.Round(YLine, 9));

        }
```

**Comment by HipsterSloth** [comment] 2016-07-19 18:22
@xMindweaverx Thanks for making that small utility. I can add it to the `misc` folder in the repo and then copy it into the builds. At some point when I'm past all of the other tasks I have to do this will get incorporated into the config tool, but this will be nice for anyone that wan't to tweak their HMD in the mean time.

**Comment by xMindweaverx** [comment] 2016-07-20 02:19
So my tool works well, but I still see ways I can simply it. Also, @cboulay , @HipsterSloth , and @zelmon64 do you know which config file in SteamVR that has those values that can be changed?

Also, cboulay you said first that it's possible to use a PS Move controller for positional tracking? I it's open and being worked on, but how close it to being ready? Thanks Guys!

**Comment by cboulay** [comment] 2016-07-20 02:46
@xMindweaverx You mean "unless a PSMove-on-head is your head-tracking method"? That's not  supported by PSMoveService directly, but anyone can use the client to do something like that.

What we might do, "someday", is provide an option in the config tool to use a controller to provide HMD pose to OpenVR. But I don't know if this would actually be useful, because any real HMD (e.g. cardboard) that would be used for rendering the scene would probably also be hooking into OpenVR's construct of what an HMD is. Can they be combined implicitly in OpenVR? I don't know enough to give an answer but I doubt it. Without trying it, my guess is that someone would need to write a custom OpenVR driver that combined PSMoveClient and <HMD_API>.

If you wanted to use the PSMove-on-head for positional tracking within Android (probably not GearVR, but maybe others), then you'd need to write some Android software that pulled controller pose information over the network using an Android build of PSMoveClient. But I guess the network latency would be pretty bothersome when it came to using the head pose to update the display, but maybe not.

**Comment by HipsterSloth** [comment] 2016-07-20 03:00
I *think* we could provide and option in the steam vr plugin to supply an HMD transform from one of the controllers, but that's definately a feature that needs to come later. There's a lot of other higher priority work we have before we could add that in. I think we actually have an issue for this request already.

**Comment by xMindweaverx** [comment] 2016-07-20 03:16
Thanks guys! Yea, no need to work on that issue. I hope to have a Vive soon. I do think adding the rest Yaw button would be a nice feature @cboulay. 

Also, I was just wonder if SteamVR had a config file to make those changes. One odd thing is that when the PS Move Service is running then steam yaw doesn't move and I never have to do the standing calibration. I just played a few rows of Gunjack and it never moved. 

It may be Audioshield that's making the changes. I need to calibrate everything and let just the PS Move Service and SteamVR set for 10 or 15 minutes and see if anything changes. 

Keep up the good work guys!

**Comment by HipsterSloth** [comment] 2016-07-23 08:12
@xMindweaverx Thanks for the tool! I just checked this into the misc/tools/win64 folder: 2e43831d67bdbd1cbaa0e64be23a0afcc1a9206f

When I make another official release I'll make sure to include the tool.

**Comment by HipsterSloth** [comment] 2016-07-23 18:48
@xMindweaverx cboulay wasn't a fan of checking executable into the repo, so I need to back this file out. Would you mind providing the source for this?

**Comment by xMindweaverx** [comment] 2016-07-23 19:47
Yea, no problem buddy.

**Comment by xMindweaverx** [comment] 2016-07-23 21:11
@HipsterSloth - Here is the project files. Note that I started the project out as PS_Move_Angle, but change the name to Rotate_Y_axis. [Download here](http://bit.ly/2a679su).

**Comment by HipsterSloth** [comment] 2016-07-24 00:04
@xMindweaverx  Relled back exe check-in. Source is now checked in to misc. 3299ebc1f816d03aa9f15d16130f601b989af184

**Comment by HipsterSloth** [comment] 2016-07-24 20:14
Updating bug title to reflect the actual remaining work item.

**Comment by nosimula** [comment] 2016-08-01 04:06
Hello guys I'm doing tests with RiftCat and to the position track I am testing the PSMoveFreePieBridge (https://bitbucket.org/hawkinse/psmovefreepiebridge) and have had good results. My biggest problem is the smartphone sensor in Vridge he always leaves the center.

**Comment by zelmon64** [comment] 2016-08-01 07:50
@nosimula Have you tried changing the tracking mode in the android part of VRidge to use one of the  magnetometer options? That should prevent the drift.

**Comment by HipsterSloth** [comment] 2016-09-29 18:03
@zelmon64 YossiMH and I have been working on this hot key reset thing over in his fork: https://github.com/YossiMH/PSMoveService

I just got it working last night. Now you can hold a psmove controller to your face and press the Start+Select buttons at the same time to align the PSMove and HMD tracking spaces. As someone who can build the service and runs rift cat would you mind building from this repo and giving this a test. If this works for you I can remove the HMD alignment step from the mat calibration tool.

**Comment by zelmon64** [comment] 2016-09-29 21:16
@HipsterSloth I've been following the exciting progress. Great work from everyone!

I built the master from YossiMH's fork and it works quite well. The building took a long time for the git clone and opencv still. I tested using three PSEyes and two PSMoves. The alignment worked great and the prompt image was good. Reorientation during game-play was fine. The touchpad emulation works well also (but I couldn't figure how to click it for the SteamVR tutorial yet). 

I also had a black screen while testing in Cosmic Trip so I tried hiding the PSMoves but it didn't have any effect. It just seems so strange that the SteamVR Dashboard shows fine but the games have to be restarted.

Sorry I haven't been more involved with the development. Just say the word if anything else general or specific needs testing ;).

**Comment by HipsterSloth** [comment] 2016-09-29 22:35
@zelmon64 Thanks a bunch for giving that a test! Much appreciated. I'm going to try and get another release out by the end of this weekend with this change in.

As for the Black Screen issue @POEDaley and I have been having a discussion about that over in issue #189. I'd actually be curious you can repro the issue with CosmicTrip but in the following scenario:

* PSMoveService is NOT running
* test_camera.exe is running

One theory I have is that is a processor issue and that the video frame extraction is soaking up too much CPU.

**Comment by zelmon64** [comment] 2016-09-30 17:23
@HipsterSloth yesterday my black screen happened only after a couple of minutes (unfortunately I don't know the cpu percentage). 
I ran for about 13 minutes with Cosmic Trip and test_camera.exe (three cameras) and the cpu sat at about 54% with no black screen. I then ran for 6 minutes with PSMoveService running and cpu at 75% (65% without SteamVR / Cosmic Trip running). I assume I tested for long enough (sorry I'm impatient) as POEDaley indicated that it's ~99% CPU that triggers it and I wasn't close. I'm using a i5-4690K at stock.

Yesterday my Samsung Note 4 was very unhappy due to the Oculus mishap and sometimes when I started Cosmic Trip the right eye would seem okay but the left would already have the black screen. Other times I kept getting a VRidge reconnecting loop.

Sorry this information probably isn't all that helpful.

**Comment by HipsterSloth** [comment] 2016-09-30 17:49
@zelmon64 That basically lines up with the result that POEDaley was seeing (PSMoveService running triggering the black screen, not test_camera). Though it is interesting that the black screen happened below the 99% threshold. It might be not CPU saturation, but rather PSMoveService not sleeping long enough in the main loop (only 1ms right now):
 
https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/Server/PSMoveService.cpp#L73

Would you mind changing that sleep time to 10 and see if that has any effect on the black screen problem.

Also what was the Oculus mishap? Some bad patch? I ask because I have Note 4 myself and I wanted to avoid any bad patches.

As always, all info is helpful. Thanks Zelmon!

**Comment by zelmon64** [comment] 2016-09-30 19:27
@HipsterSloth Oculus release an update along with "Oculus Rooms" which resulted in a background install loop. It ran the cpu near max and maxed out the internal memory read speed which made the phone run very hot while the screen was on (it seemed to pause when the screen was off). Unfortunately my auto updates were on so I was caught out by this (hopefully yours wasn't or you don't have Oculus Home installed which is why you haven't had the problem). They released a hotfix which seems to have worked (although my phone's cpu usage still seems suspiciously high but I hadn't monitored it before).

I think you may have misunderstood my testing. I was impatient so I only ran the tests for 13 and 6 minutes. I did not get a black screen that time. I'll try a bit longer (it's so boring just waiting - I think I'll put some music on this time).

**Comment by HipsterSloth** [comment] 2016-09-30 20:25
@zelmon64 Oh oops. Sorry! I interpreted "yesterday my black screen happened only after a couple of minutes" corresponded to second 6 minute test. 

I'd be still be interested in a test with the modified sleep time. Partly to see if it adversely affects PSMove tracking performance.

**Comment by zelmon64** [comment] 2016-09-30 22:44
@HipsterSloth okay so the 100% cpu seems a good way to reproduce the black screen (having a couple of google's stopwatches running does a nice job for me). I changed the setting to 10ms like you asked and noticed I was running the debug version so I swapped to release. The tracking seemed fine with 10ms but the black screen was still reproducible. So far I've only been running it with the rumble on. The back screen still seems random (once it happened when I did the start/select thingy with a controller - the rumble seemed to carry on for longer until I did that combo in a new session even though they both track fine after I do it with one). 

The following logs had black screens at the time of their names (YYMMDD-HHMM).
2308 and 2316 were with 10ms and I switch back to 1ms (Release) with 2323 (all with three cameras and two controllers running Cosmic Trip).
[160930-2218-logs.zip](https://github.com/cboulay/PSMoveService/files/503934/160930-2218-logs.zip)
[160930-2308-logs.zip](https://github.com/cboulay/PSMoveService/files/503935/160930-2308-logs.zip)
[160930-2316-logs.zip](https://github.com/cboulay/PSMoveService/files/503936/160930-2316-logs.zip)
[160930-2323-logs.zip](https://github.com/cboulay/PSMoveService/files/503937/160930-2323-logs.zip)

**Comment by HipsterSloth** [comment] 2016-10-11 18:55
Closing this issue since the feature requested has been in since the alpha-5.2 release. 

As for the black screen issue, there is another thread going on with the VRidge devs (see issue #189). It sounds like it might be a multithreading issue when multiple drivers are active in vrserver (getting a corrupted IPC message from vrserver to vrcompositor).

**Closed by HipsterSloth** 2016-10-11 18:55 UTC
Labels: task
