### ISSUE TITLE
PSMoveConfigTool crashes on color calibration

### ISSUE THREAD

**Issue by cboulay** [cboulay/PSMoveService#96] opened 2016-07-04 18:12 UTC
I can access the controller, test the rumble, calibrate the magnetometer, etc.
I can test the tracker video feed (still blank on first attempt).
However, when I attempt to color calibration, the config tool crashes (service is OK).

```
Assertion failed: (ControllerViewType == PSMove), function GetPSMoveViewMutable, file /Volumes/STORE/Tools/VR/PSMove/PSMoveService/src/psmoveconfigtool/../../src/psmoveclient/ClientControllerView.h, line 494.
Abort trap: 6
```

For quick reference, here are lines 492-496 in `class CLIENTPSMOVEAPI ClientControllerView`:
```
    inline ClientPSMoveView &GetPSMoveViewMutable()
    {
        assert(ControllerViewType == PSMove);
        return ViewState.PSMoveView;
    }
```

Unfortunately I cannot debug. Any attempt to debug PSMoveConfigTool causes Xcode to crash immediately.

**Comment by cboulay** [comment] 2016-07-04 18:36
I added some print statements to try to debug.
`std::cout << "Controller type: " << m_controllerView->GetControllerViewType() << std::endl;`

In `AppStage_ColorCalibration::request_set_controller_tracking_color`, I get -1 (i.e. "None").
In `AppStage_TestRumble::set_rumble_amount`, this returns -1 on the very first iteration then after that returns 0 (i.e. "PSMove"). The -1 doesn't trigger the crash because the call to `m_controllerView->GetPSMoveViewMutable()` doesn't get called unless m_controllerView->GetControllerViewType() == 0.

In `AppStage_ColorCalibration::request_set_controller_tracking_color` I can wrap `m_controllerView->GetPSMoveViewMutable().SetLEDOverride(r, g, b);` with `if (m_controllerView->GetControllerViewType() == ClientControllerView::eControllerType::PSMove)` and this prevents the crashing, but the controller colour is not set when first entering the app. It is set when clicking on the colour change arrow at the top right of the app.

I can use this workaround for now, but I think this bug is evident of a more systemic problem that might need fixing.

**Comment by HipsterSloth** [comment] 2016-07-04 18:43
Ah I think I know what the problem is here. The issue is that the controller view doesn't know what type it is until it get's the first UDP data frame packet back (after the client started the data stream). I had some code in the magnetometer calibration app stage that didn't advance the UI state machine until we got the first packet back. Looks like I was lazy and forgot to do the same in the color calibration tool. I can fix that now.

**Comment by HipsterSloth** [comment] 2016-07-04 19:14
I just checked in the fix for this. I tested this in Windows to make sure I didn't break anything new. Let me know if that doesn't fix OS X for you. I think long term I should probably send the first data frame with the reply to the controller stream start. That way we can guarantee that the client controller view will have data the moment you hear back that the stream is started.

**Closed by HipsterSloth** 2016-07-04 19:14 UTC

**Comment by cboulay** [comment] 2016-07-04 19:38
>I think long term I should probably send the first data frame with the reply to the controller stream start. That way we can guarantee that the client controller view will have data the moment you hear back that the stream is started.

Agreed. That also makes things simpler from the API-user's perspective.

**Comment by cboulay** [comment] 2016-07-04 19:38
Oh, and THANKS!
