### ISSUE TITLE
Black Tracker feeds when run as a server using -i command line arg.

### ISSUE THREAD

**Issue by MHDante** [cboulay/PSMoveService#350] opened 2017-01-27 07:32 UTC
When looking through earlier issues, I found that @HipsterSloth mentioned that starting the Service with the -i flag would install the Service as a windows Service. After doing so, I found that the cameras were now showing black feeds in the Tracker Video Feed.

Needless to say, Optical tracking was failing too.

I have a few assumptions as to why this might be the case: When run as a windows service, the Service's Appdata is changed to the systemprofile location (C:\Windows\system32\config\systemprofile\appdata\...)

So I think that it is storing the tracker settings there. There might be a crashed triggered when the user-level Config tool tries to access those files.

**Comment by MHDante** [comment] 2017-01-27 07:35
Just noticed the following log in the ConfigTool:

`[INFO] SharedMemory::initialize() - Opening shared memory: tracker_view_0[ERROR] SharedMemory::initialize() - Failed to allocated shared memory: tracker_view_0, reason: The system cannot find the file specified.`

**Comment by HipsterSloth** [comment] 2017-01-27 07:57
D'oh! Yeah I recently switched where I was saving the shared memory files because of a long standing issue with opening temp files in c:\ProgramData\boost_interprocess. I never tested my fix running psmoveservice as a service. Honestly I haven't use the PSMoveService as service in a long time so it's possible there are other issues with that as well.

**Comment by MHDante** [comment] 2017-01-27 08:07
Are you still planning on making the Tray application? I've seen it mentioned (as a prototype/skeleton) on #45 and in [the wiki](https://github.com/cboulay/PSMoveService/wiki/PSMoveService-Road-to-V1.0,-Draft-0). If so, do you still have it? (Do you think I could help?)

**Comment by HipsterSloth** [comment] 2017-01-27 09:03
I would love some help with this! Thanks for offering to help. I was afraid I had lost the source for the app tray stub. It was literally the first code I had written for PSMoveService, and then stuffed in a random folder. Fortunately I found it and was able to integrate into the PSMoveService cmake scripts:

https://github.com/cboulay/PSMoveService/commit/dd33c3b85d192e5cc3956d40330f2d82f745ee51

Not much to speak of. It's currently just a simple Win32 app try stub application. I modeled it after the old Oculus 0.5 SDK tray app. There are a few menus for starting and stopping the service and launching the config tool but they don't actually do anything.

Let me know if you have any questions about it. Basically everything in the app tray code is in src/apptray/psmove_apptray.cpp.

**Comment by hotdog374657** [comment] 2017-02-10 03:02
Does anyone know how to fix the black screen tracker.

**Comment by hotdog374657** [comment] 2017-02-10 03:03
Does anyone know how to fix the black screen tracker?

**Comment by HipsterSloth** [comment] 2017-02-10 08:24
I think I have a fix for this issue. We currently require PSMoveService.exe's working directory to be the same as PSMoveConfigTool's working directory. This is needed due to a quirk of how boost::interprocess handles  the shared memory path override (it has to be hard-coded to a relative path :/). The problem is that when PSMoveService runs as a windows service, by default the current working directory is `c:\windows\system`. 

To fix this I added a "--working_directory <path>" command line option that forces PSMoveService to change it's working directory to the given path at startup. We can install the service to point to the same path where PSMoveConfigTool lives. So now you can do the following:

1) open a command prompt in the PSMoveService install directory
2) run: `PSMoveService -u` to uninstall an existing service
3) run `PSMoveService -c` to check that the service is now NOT installed
4) run `PSMoveService -i --working_directory "path to psmoveservice install folder"` to install the new version of the service
5) run `PSMoveService -c` to check that the new service is installed
6) launch the windows services tool tool 
7) Verify that the command line arguments look something like the the below image and then launch the service

![image](https://cloud.githubusercontent.com/assets/16793853/22819389/be93514a-ef26-11e6-94f1-f7b1064f7193.png)

Give this test build a try:
https://drive.google.com/open?id=0B5GgUbBXlQ1uV2RlOGJoa0NMeWs

If this works I'll put out an official release with this change this weekend.

**Comment by hotdog374657** [comment] 2017-02-11 18:54
Thank you for helping m I realy needed that fix

**Comment by hotdog374657** [comment] 2017-02-11 18:55
Really I meant

**Comment by hotdog374657** [comment] 2017-02-11 21:22
Could you send me a video showing how to do this open a command prompt in the PSMoveService install directory
run: PSMoveService -u to uninstall an existing service
run PSMoveService -c to check that the service is now NOT installed
run PSMoveService -i --working_directory "path to psmoveservice install folder" to install the new version of the service
run PSMoveService -c to check that the new service is installed
launch the windows services tool tool
Verify that the command line arguments look something like the the below image and then launch the service

**Comment by HipsterSloth** [comment] 2017-02-12 05:57
There's not really much of a point in me making a video since it's literally just entering some commands into the administrator console like this:

![image](https://cloud.githubusercontent.com/assets/16793853/22859996/c2ad1322-f0a4-11e6-9dee-86793f67deb5.png)

**Comment by hotdog374657** [comment] 2017-02-13 03:49
![screenshot 4](https://cloud.githubusercontent.com/assets/25677375/22870459/7a561660-f175-11e6-82ed-13900372d289.png)

**Comment by HipsterSloth** [comment] 2017-02-13 07:09
It doesn't look like you are using the version of PSMoveService I posted. Your screen shot shows version 6.0.9.  The version I linked earlier in 7.0.5:

https://drive.google.com/open?id=0B5GgUbBXlQ1uV2RlOGJoa0NMeWs

**Comment by HipsterSloth** [comment] 2017-02-13 07:39
I formally published the release with the working directory fix. Please test against this build:

https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha7.0.7

**Closed by HipsterSloth** 2017-02-13 07:39 UTC

**Comment by hotdog374657** [comment] 2017-02-17 22:27
Ok I will
