### ISSUE TITLE
Pairing problem

### ISSUE THREAD

**Issue by eikichi09** [cboulay/PSMoveService#297] opened 2016-11-29 11:47 UTC
Hi, 
i got a problem with one of my ps move controller.
It is impossible for me to pair him. The controller tries to connect in a loop and nothing happens.
I did a screenshot to show you what error codes i get:
![psmove](https://cloud.githubusercontent.com/assets/8074503/20708778/e163084c-b631-11e6-93cf-80e54c2c65b3.png)

Can you tell me if I missed a thing or if there is a solution?

Thank you :)

**Comment by HipsterSloth** [comment] 2016-12-01 19:14
This usually is an issue with the bluetooth adapter drivers. Are you using a ASUS BT-400 or some other BT adapter? Generally in Win10 you want to use the default windows BT driver and not the drivers that come with the bluetooth adapter.

Since this falls under the troubleshooting case this sort of discussion should generally go on the psmove service forum first: 

https://groups.google.com/forum/#!forum/psmoveservice

I'm going to close this issue for tracking purposes. If after discussion it turns out to be a reproducible that that needs a tracking issue I can re-open this.

**Closed by HipsterSloth** 2016-12-01 19:14 UTC
