### ISSUE TITLE
Vr server has stopped working, oops that shouldn't have happened, a key component of steamvr is missing (everything is greyed out)

### ISSUE THREAD

**Issue by pearce31** [cboulay/PSMoveService#200] opened 2016-09-05 01:20 UTC
I setup opentrack kinect and it seems to be working. So I left it running then I did all the calibrations in psmove config tool and following vridge directions on psmoveservice wiki. So I'm done then I restart everything and steam vr always says vr server has stopped working oops that shouldn't have happened a key component is missing and everything is greyed out. I've tried lots of different steamvr.vrsettings layouts and still no differance. 

when I run just vridge steamvr says the same errors but when I delete everything in steamvr.vrsettings and run just vridge it works fine. Idk maybe I'm not setting steamvr.vrsettings correctly I'm not sure of how to set it. I set activate multiple drivers to true put in the button settings and checked it on jsonlint.com and it says it's valid.

**Comment by cboulay** [comment] 2016-09-08 15:11
I'm going through the issues and closing everything that has to do with using external applications, simply because we don't have the means or the bandwidth to debug them now and we can't verify that the problem is due to PSMoveService. I see you've already posted in the google group, thank you. We'll keep the conversation there until we can confirm that something in PSMoveService needs to change.

**Closed by cboulay** 2016-09-08 15:11 UTC
