### ISSUE TITLE
ps move not tracking correctly

### ISSUE THREAD

**Issue by oficialJCTech** [cboulay/PSMoveService#197] opened 2016-09-03 01:19 UTC
I currently have a two camera setup each camera positioned over 6 feet up (above my head) and they are a little over 5 ft apart from each other (both cameras in the front of room) and after I do the tracker poses it shows my ps move going away from the cameras when I move it vertically and does similar things moving in the z axis but moving the controller horizontally works fine. Should I be changing the positions of my cameras (I have already tried moving them farther and closer to each other) I am testing this out with steamvr with freepiebridge

**Comment by cboulay** [comment] 2016-09-08 15:13
I'm going through the issues and closing everything that has to do with using external applications (like freepiebridge, riftcat, kinect whatever, vrridge whatever), simply because we don't have the means or the bandwidth to debug them now and we can't verify that the problem is due to PSMoveService. Please post in the google group. We'll open an issue here when we can confirm that it is something that can be fixed in PSMoveService.

https://groups.google.com/forum/#!forum/psmoveservice

**Closed by cboulay** 2016-09-08 15:13 UTC
