### ISSUE TITLE
The new model of PSMove controllers do not show up (Due to new PID)

### ISSUE THREAD

**Issue by dude22072** [cboulay/PSMoveService#512] opened 2018-01-27 22:34 UTC
The new PSMoves (the micro USB ones that come with the Skyrim VR bundle) do not show up in PSMove service, whereas my old PSMove from the PS3 days shows up just fine.

The old PSMove is `VID_054C&PID_03D5&REV_0220`, which PSMoveService is programmed to look for, but the new PSMoves are `VID_054C&PID_0C5E&REV_0100`, which PSMoveService does not look for.

**Comment by cboulay** [comment] 2018-01-28 01:41
I don't have a new controller to test. Can you try modifying [this code](https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/Device/Enumerator/ControllerHidDeviceEnumerator.cpp#L26-L30) and seeing if you can get it to connect?

**Comment by dude22072** [comment] 2018-01-28 02:28
The device pairs and after pairing I have the option "Unpair USB Controller" but instead of options to configure the move I get "No connected usable controllers".

**Comment by dude22072** [comment] 2018-01-28 06:24
After further testing, when pairing and connecting a second new move it will disconnect after only a couple seconds. This happens regardless of which one I connect first. I'm using the recommended ASUS Bluetooth adaptor, and I am able to have an old move and a new move connected at the same time, so I'm not sure what the issue is.

**Comment by dude22072** [comment] 2018-02-03 23:10
Went back and also edited [this line](https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/Device/Enumerator/ControllerGamepadEnumerator.cpp#L31) and still get "No connected usable controllers" after pairing.

**Comment by dude22072** [comment] 2018-02-03 23:15
I seemed to have fixed the issue of only one move being able to connect. When I press the PS button and it connects via bluetooth Windows 10 gives me a notification saying "set up this device - Motion Controller". After clicking on it and selecting "pair" both new moves now stay connected. I still get "No connected usable controllers" in PSMoveService, though.

**Comment by ItSaM3** [comment] 2018-02-07 19:39
I have the same problem and am a noob at editing code, could you upload a video or email it to brandon.larg@gmail.com so I could connect my move controllers too. 👍

**Comment by jmbrysk** [comment] 2018-03-04 02:28
@cboulay, I was able to reproduce what @dude22072 is seeing. Are there any other changes that can be made to the existing code or do you think that the protocol has changed and requires a massive rewrite?

**Comment by cboulay** [comment] 2018-03-04 03:21
@jmbrysk and @dude22072 ,
I'm sorry but I'm afraid I don't have time to buy a controller and debug this. If either of you are comfortable debugging C++ code, you should probably start off using one of the tests (instead of the full PSMoveService). Put a breakmark [here](https://github.com/cboulay/PSMoveService/blob/master/src/tests/test_psmove_controller.cpp#L26). Step into that, and see where it fails. It'll be interesting to know whether or not you make it to the end of [this block](https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/PSMoveController/PSMoveController.cpp#L410-L460), or further.

**Comment by jmbrysk** [comment] 2018-03-04 03:27
No worries - I appreciate the advice though. I'll try to get to this in the next few days and report back with what I find!

**Comment by shenmohao** [comment] 2018-03-14 13:27
have u sloved this problem?

**Comment by dan2wik** [comment] 2018-03-15 00:31
From what I could tell, the new PS move controllers have some large protocol changes and would take a bit of effort to get working again.

**Comment by shenmohao** [comment] 2018-03-15 02:45
fine, I just bought two psmove yesterday. hope it can be solved

**Comment by BoopityBoop** [comment] 2018-03-27 23:41
Damn, wish I'd known this before buying all the stuff for it on PC...

**Comment by anotherannoyeduser** [comment] 2018-03-28 05:19
Yeah I just went out and bought some of the parts today too, only to learn that the hardware I already had, which was my excuse for going this rout instead of NoloVR, is incompatible because it's too new. I hate to be a whiny user, but a lot of us have been having this issue and it's a major problem, and it's been over half a year. please update your software.

**Comment by dude22072** [comment] 2018-03-28 05:33
Later models of the PS3 compatible moves (after the PSVR release but before the PS4 only moves) had the magnetometer disabled. Supporting the PS4 moves would provide no different an experience than using these late PS3 moves, which already work.

**Comment by cboulay** [comment] 2018-03-28 05:50
Maybe @anotherannoyeduser should become @anothercapableprogrammerthatisntsoentitled

**Comment by anotherannoyeduser** [comment] 2018-03-28 10:19
I didn't mean to offend. Programming is well outside my skillset, but I was thinking of making a material investment in the project. 

not wanting to spend money/time getting one of the new controls that's giving everyone guff seemed to be part of your concern, and I'll have spares once I get my impatient, entitled ass to a store to get some second hand PS3 move controls. if there's a PO box or some such I could mail the thing to, I'd be more than happy to provide you with one of the controls that came bundled with skyrim VR for you to do testing and bug chasing with.

**Comment by mhuber161** [comment] 2018-04-05 08:29
> I don't have a new controller to test. Can you try modifying this code and seeing if you can get it to connect?
Edit: Might be necessary here too.

> I'm sorry but I'm afraid I don't have time to buy a controller and debug this. If either of you are comfortable debugging C++ code, you should probably start off using one of the tests (instead of the full PSMoveService). Put a breakmark here. Step into that, and see where it fails. It'll be interesting to know whether or not you make it to the end of this block, or further.

@cboulay I followed your instructions and was able to get the new PSMove controller with PID_0C5E to rumble and flash lights by running test_psmove_controller. I can work on this more if you could give me some guidance as to what parts of the code need updating.

**Comment by cboulay** [comment] 2018-04-13 19:15
@mhuber161 That's great. I'm sorry I didn't see this message sooner. Well, I'm sure I did, but I must have looked at it while half asleep and forgotten. I need to stop sleep more.

It's hard to say what needs to be done. We didn't really design this with having multiple models for the same device in mind. So there are places where the model number is hard-mapped to the device type. So I guess the options are to either (a) redesign the device enumeration scheme so that multiple model numbers can be defined for any device type, or (b) create a new device type, then anywhere the device type is used to determine the code path (i.e., in a switch or if-else block) then we need to duplicate the code for the new device type.

(a) is the correct way to do it, and is more future proof, but it also requires a little more thinking and time to get familiar with the code.

In either case, most of the changes will be in [Device/Interface/DeviceInterface.h](https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/Device/Interface/DeviceInterface.h) and [Device/Enumerator/ControllerHidDeviceEnumerator.cpp](https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/Device/Enumerator/ControllerHidDeviceEnumerator.cpp).

**Comment by pigmater** [comment] 2018-06-16 01:46
Hey @cboulay when I went to Walmart I found the new models on sale look! https://ibb.co/e6xdkJ You can tell its the new because of the middle button not being  transparent from the old version https://ibb.co/nQi4sy

**Comment by HipsterSloth** [comment] 2018-06-22 07:57
@mhuber161 I finally got my hands on one of these problematic controllers. I was able to get the host bluetooth address written to the controller using the psmove_config pairing tool. However I keep getting presented with the windows device pairing dialog when turning on the controller (holding down the PS button):

![image](https://user-images.githubusercontent.com/16793853/41764726-de6b21d8-75b6-11e8-8433-47f7b27e6809.png)

When I accept the pairing the controller turns itself off. I was able to verify that the controller was connected for a brief moment by adding a hook in the DBT_DEVICEARRIVAL callback in PlatformDeviceAPIWin32.cpp to immediately open the controller's bluetooth HID device. It can open the device at that point, but I can't do anything with the open connection and then it closes right away.

Did you have this problem? I'm curious how you got test_psmove_controller running.

**Comment by cboulay** [comment] 2018-06-22 19:06
https://github.com/thp/psmoveapi/issues/353

**Comment by uslucad** [comment] 2018-06-23 09:31
@HipsterSloth
I do not speak English well, so I write it with a translator. I'm sorry.
I have the same problem at the moment, and this is estimated to be a problem with certain builds of Windows 10. Because Dual Shock 4 on Windows 10 has the same problem, and Dual Shock 4, which can use the pairing mode, is normally paired when connected to MacBook Pro.

**Comment by HipsterSloth** [comment] 2018-06-28 05:38
I've looked into the new ZCM2U a bit more. It's definitely more than just a change of PID. I cracked the ZCM2U open and verified that it has different ICs in it:

* MediaTek ARM MT 3610N (I think this is a "System on a Chip" that is both a microcontroller + bluetooth receiver)
* D26736 (unknown)
* KKB733 (Unknown, 3 of these, very small)
* MD NF9H C3F
* TC 7736FTG 7329F1 (Unknown, but this same chip is on the DualShock4)

You can see a breakdown of the ICs on the older ZCM1U here:
https://www.ifixit.com/Teardown/PlayStation+Move+Teardown/3594

Further it looks like the HID reports (the messages the controller talks back to the PC over USB with) have quite a few changes. I extracted these using Usblyzer while each controller is connected over USB. The report used to fetch the bluetooth address appears to be the same, but almost all of the other reports have at least a few small changes. There are also a bunch of new reports.

[HID_Reports.zip](https://github.com/cboulay/PSMoveService/files/2143886/HID_Reports.zip)

I was able to verify that the calibration data HID report changed too. It looks like it has only one block instead of two. 

As for the bluetooth pairing issue, my current best guess is that the new controllers are using Bluetooth 2.1 "Simple Secure Pairing" with either a hard-coded pin or are fetching the PIN with a HID report when connected via USB:

https://en.wikipedia.org/wiki/Bluetooth#Bluetooth_2.1_+_EDR

All this is to say, adding support for these controllers isn't just a simple upgrade. This is going to be a lot of work figuring out how to get this controller pairing and supporting the newer HID reports.

I'm happy to help support anyone that wants to dig into this further, but I'm personally more interested in focusing on the multi LED tracking work that I've been working on over the last few months.

**Comment by pigmater** [comment] 2018-06-28 05:59
@HipsterSloth Does this mean it will be a while until the new controllers are supported?

**Comment by HipsterSloth** [comment] 2018-06-30 22:36
@pigmater Unless someone else is willing to volunteer their time trying to reverse engineer both the bluetooth connectivity issue and the new HID packet format, then yes it will likely be a while.

**Comment by HipsterSloth** [comment] 2018-07-09 08:37
@cboulay Oh that's awesome they figured out the hid packet changes! Also encouraging that it's possible to pair the newer controller without any custom bluetooth auth shenanigans. I'd love to understand how bluez in linux handles pairing differently from the windows bluetooth stack.

**Comment by nitsch** [comment] 2018-07-09 09:29
@anotherannoyeduser

> if there's a PO box or some such I could mail the thing to, I'd be more than happy to provide you with one of the controls that came bundled with skyrim VR for you to do testing and bug chasing with.

Does that offer still stand? How much would shipping to Austria or Germany cost you?

**Comment by HipsterSloth** [comment] 2018-08-21 16:11
> Simply answer HCI PIN Code Requests from the controller with PIN code '0000'.

@nitsch Thanks for this tip! I finally got my ps4 controller paired using BluetoothAuthenticateDevice and related functions (see https://docs.microsoft.com/en-us/windows/desktop/api/bluetoothapis/nf-bluetoothapis-bluetoothauthenticatedevice), which allows a pin to be set. It's still is a bit timing sensitive, so I still have some work todo making that process more seemless. If I can can make it work without much end user hassle I'll make a PR to psmoveapi with a tweak to the windows pairing code.

**Comment by HipsterSloth** [comment] 2018-08-25 07:59
I just checked in my progress so far in the ZCM2 branch in case anyone was curious:

https://github.com/cboulay/PSMoveService/commit/cf60bf23aa3da88e28f14bea8ac3d68cbcb53220

Gyro calibration parsing still needs work. The current gyro calibration parsing code is basically just a big pile of guesses at the moment and the current result drifts pretty bad. @nitsch started an e-mail thread with me today about decoding the calibration.

**Comment by gb2111** [comment] 2018-08-30 11:07
@HipsterSloth 
i was able to build branch and tried new ps move. i have model ZCM2E.

when pairing a message from widnows will appear that there is new device pairing. you need click it and confirm to pair new device and continue pressing PS button to finish pairing also by psmoveservice.

then I have cases when it paired somehow only for windows bluetooth but somehow did not complete process for psmoveservice. in such case controller was shown as paired or even connected in bluetooth list but not picked up by psmoveservice.

when it pair properly and is connected via usb it still shows in config tool as it was not paired. only pair button. previous version let you use controller when paired and connected via usb.

finally when paired, it works only 2 seconds and disconnect. when press PS again it will work another 2 seconds.

i think this might cover your results. if there is any specific case you want to test please let me know.

**Comment by gb2111** [comment] 2018-08-31 12:36
i did more testing today. really hard to give some specific report. mostly due to bluetooth pairing.
sometimes action is not complete until you confirm via windows UI. and when you confirm it might be not available cause connection was lost.

**Comment by gb2111** [comment] 2018-09-02 20:12
i did even more testing and it seems like after windows update 1803 I can pair new ps move and use it. it might take you to do it properly as whole process is sensitive to when you click on prompt window from bluetooth :) then you need restart pc. and after pressing PS button it stays connected :) i think it dropped off on few test cases but it was after few minutes and reconnected immediately and in most cases was working very long.
i tested on 4 PC and it worked on 3. one has issue with prompts as they were not arriving until I clicked bluetooth icon. i think then it could be too late... not sure.

**Comment by nitsch** [comment] 2018-09-03 06:17
@gb2111 It might be helpful to run Wireshark on the Bluetooth interface
and send @HipsterSloth a capture that contains successful connection,
losing the connection, reconnects etc. along with with annotations when
you did what (Wireshark adds timestamps to the events, so your actions
can be correlated to events in the capture).

**Comment by pbassut** [comment] 2018-09-08 06:31
I'm subscribing to this thread!
First of all, great work folks.

I also have the ZCM2U model and facing the same issue. Looks like since it's gonna be a lot of work to get it working, maybe we should add a warning on the config tool saying the model isn't compatible yet?
Guess this can be done using the product_id/vendor_id? Just to avoid frustration from users and since it seems relatively simple to implement.

**Comment by pbassut** [comment] 2018-09-08 06:32
I don't do windows dev but I'm willing to get my hands dirty if the project is gonna make good use of such a feature.
I'm putting Windows in a VM just now

**Comment by HipsterSloth** [comment] 2018-09-11 07:11
@pbassut A warning for the time being seems like a good idea. If that's something you wanted to try implementing I'd be happy to advise and take a PR.

**Comment by gb2111** [comment] 2018-09-11 17:18
@HipsterSloth 
tried this build. could not connect to any existing controller. also i see any controller when I connect usb which was never case when I tried build after [this post](https://github.com/cboulay/PSMoveService/issues/512#issuecomment-415951213)

**Comment by HipsterSloth** [comment] 2018-09-13 07:01
@gb2111 I just did a fresh sync and compile to verify that this works. Everything looks fine to me. That particular file got added as part of this new submodule:

https://github.com/cboulay/PSMoveService/commit/121566d69e457b7f96464fc521b50018b84faabb

Maybe try this on the command line in the PSMoveService folder:

git submodule foreach --recursive git submodule update --init

**Comment by gb2111** [comment] 2018-09-20 10:13
@HipsterSloth 
I tried command, no help.

I entered your branch via portal:
https://github.com/cboulay/PSMoveService/tree/ZCM2U

Downloaded code and unpacked. File readerwriterqueue not there :(

**Comment by nerionx** [comment] 2018-09-20 12:13
I didnt use the command 

I downloaded the source for the module https://github.com/cameron314/readerwriterqueue

and dropped it into the third party folder thirdparty/lockfreequeue
then compiled and it built fine.

Can pair and use them successfully, but yea drift is bad

**Comment by gb2111** [comment] 2018-09-20 17:45
@nerionx thanks for help. that worked. I copied project to lockfreequeue in third party folder and that helped.

@HipsterSloth the folder is created but it is empty.

Guys, I am curious how is stable bluetooth connection for you ?

I found that in below path there is ConnectionAuthenticated setting. Sometimes it is 1 and sometime it is 0. 

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HidBth\Parameters\Devices\

I have now two controllers paired and value is 1. One works continously but other disconnects after 2-3 seconds. I guess it is somewhere not authenticated but have no clue where :) I tried unpair it with hope it will clear all settings but it does not help.

Any ideas?

**Comment by nerionx** [comment] 2018-09-20 19:00
Stable used them for over an hour, they dont like having low batteries though, would turn off after a matter of seconds if they had <20%

**Comment by nerionx** [comment] 2018-09-20 19:02
Also pairing can be a pain, I found it was easier if i left the bluetooth window open when i paired so I could quickly accept it when the popup happens

**Comment by HipsterSloth** [comment] 2018-09-23 01:33
And in case anyone is wondering I tested this in SteamVR using Space Pirate Trainer. Left controller was the old PS3 controller and the right was the new PS4 controller:

![image](https://user-images.githubusercontent.com/16793853/45923252-dce1f300-be95-11e8-9ce5-e241c8751e48.png)

**Comment by nerionx** [comment] 2018-09-23 07:30
Setup:
Windows 10
Nvidia 1060 6gb
AMD 8350 4ghz
2x PSMove controllers ZCM2E
ALVR - Oculus Go
Driver4VR - Kinect tracking

Both paired fine, colours set correctly and standard tests work fine. 

The drift when the controllers are not moving is much improved, near enough spot on for 1 controller the other has a very slight drift still

When moving they move out of alignment (i guess this is always going to happen?) but its no where near as bad as before although this is probably because they no longer do a full 360 every 20 seconds or so when stationary.

I will play some games later and see how usable they are but I imagine they should work fine.

**Comment by gb2111** [comment] 2018-09-23 17:45
hi, i have also tested 2 x new ps moves.
the drift seem to be really small and the orientation is reacting very good to physical orientation.
pairing process has changed a bit I think, not sure exactly where :)

during one test both were working quite long time. other time, one or even two stopped after some time. 
logs were same as [here](https://github.com/cboulay/PSMoveService/issues/512#issuecomment-423549675). one controller remains on and is seen as connected on bluetooth manager.

[2018-09-23 19:42:01.726]: ServerDeviceView::poll - Device id 1 closing due to no data (100 failed poll attempts)
[2018-09-23 19:42:01.731]: PSMoveController::close - Closing PSMoveController(\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&0c5e&col01#8&bb483a&1c&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})

i am suspecting that this happens when I leave controllers still on the table but need do more testing.

**Comment by nerionx** [comment] 2018-09-23 18:45
So I have messed about a bit more today, and I have some bad drift still, it can be seen after calibration but its at its worse when you bank the controller, whichever direction you rotate to, the yaw? also rotates in the same direction.. I have uploaded a video to hopefully show you what i mean

https://youtu.be/Idat8AA6lgM

**Comment by nerionx** [comment] 2018-09-23 19:27
Played some games, i had some issues but I think it might of had something to do with me using a compiled older version before hand, repairing the controllers fully fixed it, played the lab and rec room both worked fairly well

**Comment by HipsterSloth** [comment] 2018-09-23 22:01
@gb2111 I'm wondering if you are getting USB bandwidth saturation with two controllers connected. The issue you are describing looks exactly like what happens when too much data is getting sent over the same USB root hub (one controller stops getting HID updates and disconnects). You might try moving you bluetooth dongle to a different USB port and see if that helps.

Of course if that is true, why did you not have this problem with two older PSMove controllers? I think the ZCM2U might use more bluetooth bandwidth than before. The ZCM1U stored two Accelerometer / and gyro updates per HID packet, while the ZCM2U only has one. I suspect that the ZCM2U might send update packets faster to compensate for half the sensor data per packet, but I haven't actually measured this so I could be wrong. 

@nerionx Thanks for testing this! Glad to hear the controllers performed decently in games. I would definitely expect the bit of yaw drift over time you were seeing without a magnetometer. I'm hoping I can improve this with the "optical yaw correction" I spoke of previously. I took a stab at this in my last check-in. You can test this by changing the orientation filter to "Complementary Optical ARG". I had mixed results. It always wanted to adjust the yaw straight forward for me, which makes me think it's not computing the optical yaw correctly. I won't hold up the release on that feature though. I can finish that up in a hot fix later once I get it working (and that might take me some time).

**Comment by nerionx** [comment] 2018-09-23 22:44
@gb2111 I have my dongle in my front case ports, and cameras etc in the back. I read that these can be 2 separate hubs on your motherboard, doesn't sound right to me but it seems to work.
My dongle is the USB-BT400 that seems to be recommended alot and its cheap as chips.

@HipsterSloth The filter do I need to anything other than change it? Does it require the pseyes? (optical)

**Comment by HipsterSloth** [comment] 2018-09-24 00:04
@nerionx The new filter does require the usage of the PS3Eyes since it combines optical data with the sensor data to estimate the orientation. You'll want to set the filter in the controller settings and then test it using the "Test Tracking Pose" option under the tracking settings. Make sure you have the correct controller selected:

![image](https://user-images.githubusercontent.com/16793853/45934407-a61de280-bf52-11e8-9394-281e255a3ca9.png)

**Comment by nerionx** [comment] 2018-09-25 12:11
Sorry it took me a while, I have tested your filter.
Firstly I learnt RED led tracking is terrible dont use red. Had some sucess with blue and green
The drift is still there but it has changed axis and it is much slower, Its now up drift rather than left to right. While this isnt ideal its makes games infinitly more playable on this axis. I had a few plays of beat saber and was able to finish the courses which I wasnt able to do before

**Comment by gb2111** [comment] 2018-09-25 15:37
hi. i tested both controllers now and then work like 30 minutes and don't disconnect :)
anyway I am curious why when issue happened, controller not only lost tracking but also disconnected. so it remained visible on list of devices but on listed on psmoveservice.
any idea or code reference what can be reason of that ?

**Comment by HipsterSloth** [comment] 2018-09-25 16:54
@gb2111 I am not sure exactly sure why that would happen, but like I said before, the most likely explanation is USB bandwidth saturation. The controllers would appear to be connected because they are registered in windows, but when PSMoveService tries to communicate with them the hid_read request is timing out because there is too much traffic on the USB root hub. That error condition is reported here:

https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/PSMoveController/PSMoveController.cpp#L1064-L1072

If a controller fails too many hid_reads, we disconnect the control. That happens in ServerDeviceView.cpp:

https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/Device/View/ServerDeviceView.cpp#L69-L78

Alternatively I could add an automatic close and reopen the controller in this case. But that wouldn't really fix the issue of not having enough USB bandwidth. The controller tracking would just halt on occasion during gameplay.

@nerionx Thanks for giving the new filter a test. That's the definitely behavior I was seeing as well. After I get this release out I'll look into improving that filter as part of some other general tracking changes I'm working on.

I have one small fix to make in this branch, and then I'll publish an official PSMService release later this week.

**Comment by HipsterSloth** [comment] 2018-09-26 16:04
@gb2111 The new "ComplimentaryOpticalARGFilter" can be used on either the PS4 controller or the PS3 controller without a magnetometer. However that filter still needs work. I'm planning on continuing to work on it after this next release.

**Comment by gb2111** [comment] 2018-09-26 20:17
ok. so I changed code a bit and I only logged when m_pollNoDataCount > 100 but keep it running until > 5000. And I noticed in logs that one controller 3 times exceeded 100 but was ok later what means it did not exceed 5000 and recovered. 
Then I wanted to check what is level it comes back with data but then I tried for few hours and it did not happen :)

I will try more to see what level is this and also find answers to those questions:
- Will this happen only for one controller?
- What is error message?
https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/PSMoveController/PSMoveController.cpp#L1070
- Why it happens sometimes and sometimes no.

It is only me right now. But... perhaps we can increase limit as it practically will not affect anything.

One more thing. When I restarted service, all devices were detected. So question is if we really need to close connection or just stop controller?
https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/Device/View/ServerDeviceView.cpp#L75

**Comment by HipsterSloth** [comment] 2018-10-01 01:56
There is now an official release out with support for the ZCM2:

https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha9.0.0

There will be ongoing working improving gyro drift and controller timeout issues, but that can come in future releases/hot-fixes. I'm going to mark this issue as resolved for tracking purposed, but please feel free to continue discussing in the thread as new issues come up with this release.

**Closed by HipsterSloth** 2018-10-01 01:56 UTC

**Comment by T6BERRY** [comment] 2018-11-24 23:58
I have a very strange issue.  I connected my CECH-ZCM2N controllers before I even knew about this issue using a version of moveservice that was not updated from them.  They connected just fine and I was able to preform all calibrations as normal.  Then after pairing with my PS-Pro for a bit I can no longer pair them with my PC, even running the version of psmoveservice that was developed for them in the above link. This is the error:
libusb: error [init_device] device '\\.\USB#VID_054C&PID_09AF&MI_07#6&1BC97705&0&0007' is no longer connected!
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
[2018-11-24 15:41:01.398]: MorpheusHMD::open - Opening MorpheusHMD(USB\VID_054c&PID_09af).
[2018-11-24 15:41:01.400]: MorpheusHMD::open - Morpheus command interface is flagged as DISABLED.
[2018-11-24 15:41:01.402]: MorpheusHMD::open - Failed to open MorpheusHMD(USB\VID_054c&PID_09af)
[2018-11-24 15:41:01.405]: MorpheusHMD::close - Closing MorpheusHMD sensor interface(\\?\hid#vid_054c&pid_09af&mi_04#7&231ab13e&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})
[2018-11-24 15:41:01.407]: DeviceTypeManager::update_connected_devices - Device device_id 1 (USB\VID_054c&PID_09af) failed to open!
I tried to mod MorpheusHMD JSON file as was advised in a different issue report but there is no such file in the APPDATA for psmoveservice.  I'm so stuck I've been at this all day and nothing has worked.

**Comment by WiksterRvN** [comment] 2020-01-05 17:43
After  pairing my controllers doesn't appear in th window 
![image](https://user-images.githubusercontent.com/59516160/71783723-3159a500-2feb-11ea-943e-1da535bd3c93.png)
