### ISSUE TITLE
Mapping Vive controller input to Xbox controller

### ISSUE THREAD

**Issue by NeoToriyama** [cboulay/PSMoveService#82] opened 2016-06-29 06:26 UTC
DISCLAIMER: This is not actually an issue with the PSMoveService, but I'm unsure where to post this, but I saw an issue on here which covered a similar topic. 

So, I got the position of SteamVR mapped to an Xbox controller using FreePIE, while using the Revive patch with Riftcat/Vridge, but what about the Vive controller(s)? How can I map it's position to the Xbox controller? Also it's various buttons (Menu button, Trackpad, Trigger, Grip Button)? I'm more than willing to put in the work, just need to know if it's possible.  I was thinking it could be mapped to the analog sticks similar to how the Dolphin Emulator maps the Wiimote motion features and buttons to a controller.

**Comment by zelmon64** [comment] 2016-06-29 07:54
> So, I got the position of SteamVR mapped to an Xbox controller using FreePIE, while using the Revive patch with Riftcat/Vridge

@NeoToriyama I'm getting a little muddled and am not quite sure what you mean by this. What I mentioned in #80 was to use an xbox controller as an **input** to FreePIE which then sends the data **to** VRidge **via** FreeTrack. If you want to control a **virtual** Vive controller with a **real** xbox controller then you can do that by using the Hydra emulation in FreePIE. 

On the other hand, if you want to **emulate** an xbox controller with a **real** vive controller then that is not yet possible. The addition of Vive controllers to FreePIE was mentioned [here](https://github.com/AndersMalmgren/FreePIE/issues/85). Anders states that someone should be able to write a Vive controller plugin for FreePIE using the [OpenVR API](https://github.com/ValveSoftware/openvr) but to my knowledge no one has done this yet.

**Comment by NeoToriyama** [comment] 2016-06-29 08:05
"I'm getting a little muddled and am not quite sure what you mean by this. What I mentioned in #80 was to use an xbox controller as an input to FreePIE which then sends the data to VRidge via FreeTrack."

Yeah, I was able to do that, and it works really well.

 "If you want to control a virtual Vive controller with a real xbox controller then you can do that by using the Hydra emulation in FreePIE."

Yes! This is what I was asking basically. Do I need the Hydra controllers for this? Or is there some sort of script that allows Hydra emulation?

"On the other hand, if you want to emulate an xbox controller with a real vive controller then that is not yet possible. The addition of Vive controllers to FreePIE was mentioned here. Anders states that someone should be able to write a Vive controller plugin for FreePIE using the OpenVR API but to my knowledge no one has done this yet."

This is interesting, but I'm not too worried about this as my headset hasn't arrived yet, but I like the idea. Thank you for the feedback. It's much appreciated.

**Comment by NeoToriyama** [comment] 2016-06-29 08:17
Okay, so I found the script for Hydra emulation and downloaded the Sixsense SDK for Razer Hydra from the Steam, what would be my next step?

**Comment by zelmon64** [comment] 2016-06-29 08:27
@NeoToriyama Ah I see. Follow [this guide](http://talesfromtherift.com/play-vive-vr-room-scale-games-with-the-oculus-rift-razer-hydra-motion-controllers/) to enable hydra support in SteamVR. Then copy the "fake" sixense.dll files from FreePIE and replace the originals in `C:\Program Files (x86)\SteamVR Hydra driver\hydra\bin`. We discussed how to use this method in [this mtbs3d thread](http://www.mtbs3d.com/phpBB/viewtopic.php?f=139&t=18265).

**Comment by NeoToriyama** [comment] 2016-06-29 08:29
Okay, thank you, I'll do that and report back on my progress.

**Comment by NeoToriyama** [comment] 2016-06-29 09:08
Okay, so everything is installed and the "fake" .dlls have been replaced and I've got the script ready for FreePIE, how would I enable this to work with Vridge?

**Comment by NeoToriyama** [comment] 2016-06-29 09:20
I get this error upon running the script: 

"USAGE - BOUND CONTROLLERS:
Press the the left psmove "Move" button
Press the left nagivation controller POV down"

I don't have PSMove controllers, so I believe that's why it won't run, how to do I make it work with just the Xbox controller?

**Comment by zelmon64** [comment] 2016-06-29 09:24
@NeoToriyama That should be it. VRidge is just a HMD emulator so it has nothing to do with the controllers. When you run SteamVR it should now display a green message about the hydra controllers and show two active controllers in the SteamVR Status window.

**Comment by NeoToriyama** [comment] 2016-06-29 09:26
Okay, so in regard to the files I need to replace, there's "Win32" and "Win64" folders, do I replace the .dlls in both folders?

**Comment by zelmon64** [comment] 2016-06-29 09:29
I replaced both to be on the safe side but probably just the Win32 one would be enough.

**Comment by NeoToriyama** [comment] 2016-06-29 09:29
Okay, I'll try that.

**Comment by NeoToriyama** [comment] 2016-06-29 09:37
Yeah, so everything is done to the letter, but the script I'm using won't run, I'm assuming I need the script running in order for the controllers icons to light up on Steam VR?

**Comment by NeoToriyama** [comment] 2016-06-29 09:50
Just a basic script, well as basic as it can be, that maps all possible controls from a Vive controller to an Xbox controller. That includes movement of the controller in the virtual space, however that's much possible. Or possibly a configuration you think works best? It would be a great deal of help.

**Comment by zelmon64** [comment] 2016-06-29 10:00
I'll get started on this. In the mean time, I checked and the controller icons should light up on SteamVR even if FreePIE isn't running at all. Did you install v1.0.1.12?

Since this doesn't have anything to do with PSMovveService I think we should move this discussion. If you could please close this issue and I'll start a new thread in the FreePIE section on mtbs3d?

**Comment by NeoToriyama** [comment] 2016-06-29 10:08
Yes, I installed the latest version of the drivers, but I believe my issue lies with the files I have to replace, I think I'm not replacing them correctly, and yes I'll close it now and move this issue.

**Closed** 2016-06-29 10:12 UTC

**Comment by NeoToriyama** [comment] 2016-06-29 10:52
I got the controller icons to show up now, I replaced the wrong files, all is working good so far.

**Comment by zelmon64** [comment] 2016-06-29 11:44
I created the new thread [here](http://www.mtbs3d.com/phpBB/viewtopic.php?f=139&t=22033) and posted a script. It seems to be emulating the hydra fine but the integration with SteamVR doesn't quite work.

**Comment by weedamon** [comment] 2017-06-19 06:31
Zelmon64 can you upload it to dropbox or mediafire and post it here?

**Comment by HipsterSloth** [comment] 2017-06-19 06:53
@weedamon FWIW if your goal it to get a tracked xbox 360 controller I just put out a release of of PSMoveSteamVRBridge that adds support for this. Check out the setup notes here and see if that's what you were looking for: https://github.com/HipsterSloth/PSMoveSteamVRBridge/wiki/Virtual-Controller-Setup

**Comment by weedamon** [comment] 2017-06-19 07:46
@HipsterSloth i dont have a led light nor a ball any altenitives?

**Comment by zelmon64** [comment] 2017-06-19 08:21
@weedamon here is the FreePie script and the two "Fake" dlls:

https://drive.google.com/open?id=0B7SYYOqNW4FSNlB6NTVsSTVpTEk
https://drive.google.com/file/d/0B7SYYOqNW4FSbkJ1amJPNnJkRmM/view?usp=docslist_api
https://drive.google.com/file/d/0B7SYYOqNW4FSbE1IUjFPbVRWY1U/view?usp=docslist_api﻿

**Comment by weedamon** [comment] 2017-06-19 08:41
Do you need to replace the dlls again?

**Comment by zelmon64** [comment] 2017-06-19 08:54
@weedamon those are the original "Fake" dlls which differ slightly from the ones bundled with the current release of FreePie in the way they handle the orientation. If you already have these exact dlls in `Steam/steamapps/common/SteamVR Driver for Razer Hydra/hydra/bin` then there's no need to replace them again.

**Comment by weedamon** [comment] 2017-06-19 09:12
how do you get the green thing to go

**Comment by zelmon64** [comment] 2017-06-19 10:01
I just installed it to remind myself. To press the buttons you can pull the triggers. To press both System buttons either simultaneously press START and BACK or hold a bumper and press either START or BACK (sometimes trying to press the buttons simultaneously doesn't work).

I'm not seeing the virtual models though so something might be broken with the driver. It's last update was 6 Aug, 2016. OpenVR has changed quite a bit since then.

**Comment by weedamon** [comment] 2017-06-19 10:47
it doesnt work

**Comment by zelmon64** [comment] 2017-06-19 11:03
I'll need a bit more to go on than that. I just installed it all on my system and it works so it should work. What errors are you getting?

**Comment by weedamon** [comment] 2017-06-19 11:06
im not getting errors it just wont go away

**Comment by zelmon64** [comment] 2017-06-19 11:09
In FreePie can you see the button presses being detected in the `watch `tab?

**Comment by weedamon** [comment] 2017-06-19 11:11
didnt think XD going to when i get chance

**Comment by weedamon** [comment] 2017-06-19 11:22
it works but it wont be in front

**Comment by weedamon** [comment] 2017-06-19 11:22
of me

**Comment by zelmon64** [comment] 2017-06-19 11:35
To get the controllers in front of you realign them with a bumper and START/BACK then keep the bumper held and press up on the D-pad. The controllers should then move forward.

**Comment by weedamon** [comment] 2017-06-19 14:16
how do i re align cause it wont work

**Comment by zelmon64** [comment] 2017-06-19 14:31
Realign by either simultaneously pressing START and BACK or hold a bumper and press either START or BACK (both of these methods should make it think that you pressed the start buttons on both of the Hydra controllers). I've tweaked the script a little which may make it easier:

https://drive.google.com/open?id=0B7SYYOqNW4FSQUxCUlFFc3kxY28

After the realignment is triggered the virtual controller models should be either side of your head. btw what HMD are you using? I've only confirmed this to work with VRidge.

**Comment by weedamon** [comment] 2017-06-19 15:14
never mind

**Comment by weedamon** [comment] 2017-06-19 15:25
can you create list of controls

**Comment by weedamon** [comment] 2017-06-19 15:42
btw thanks for helping

**Comment by zelmon64** [comment] 2017-06-19 16:12
Okay, here's a quick run through of v0.4.1 [to do something = what you do]:

* left x and y dir move = leftStick
* left reset position = leftThumb
* left trigger = leftTrigger
* left start= back
* right x and y dir move = rightStick
* right reset position = rightThumb
* right trigger = rightTrigger
* right start= start
* leftShoulder held:
  - left pitch = leftStickY
  - left yaw = leftStickX
  - left reset orientation = leftThumb
  - both z-dir move = D-pad vertical
  - left roll = D-pad horizontal
  - left button one = a
  - left button two = b
  - left button three = x
  - left button four = y
  - left bumper = leftTrigger fully pulled
  - leftTrigger partially pulled:
    - left joybutton = leftThumb
    - left joystick = leftStick
  - both start = start or back
* rightShoulder held:
  - right pitch = rightStickY
  - right yaw = rightStickX
  - right reset orientation = rightThumb
  - right z-dir move = D-pad vertical
  - right roll = D-pad horizontal
  - right button one = a
  - right button two = b
  -right  button three = x
  - right button four = y
  - right bumper = rightTrigger fully pulled
  - rightTrigger partially pulled:
    - right joybutton = rightThumb
    - right joystick = rightStick
  - both start = start or back
* A or B button held:
  - use leftStick and D-pad to send FreeTrack data for RiftCat

It might not be complete.

**Comment by weedamon** [comment] 2017-06-19 17:06
i cant make it forwards and back
