### ISSUE TITLE
Move Lights turn off 5-10sec after startig steamvr

### ISSUE THREAD

**Issue by marcos10soares** [cboulay/PSMoveService#300] opened 2016-12-01 11:50 UTC
The controllers are both connected when steamvr is started, after about 5-10sec the lights turn off and after 1 minute or 2 the controller symbols turn gray.

I checked if PSMoveService was running (and it was), I was able to open PSMoveConfig and confirm that both controllers are still connected and working.

How can I solve this?

PS: also sometimes only one controller shows up as connected in steamvr (randomly)

**Comment by POEDaley** [comment] 2016-12-01 12:24
This sounds like a bandwidth problem.  Try plugging the Bluetooth dongle into another USB port.  If you can move it to a USB 3.0 port, that is ideal since it's a completely different controller.

**Comment by marcos10soares** [comment] 2016-12-01 12:31
It was on a usb3.0 port on the front panel, but changed it to a usb3.0 on the back panel, still the same problem :/

![capture1](https://cloud.githubusercontent.com/assets/7953349/20794070/18c58030-b7c2-11e6-999e-420774dec9ad.PNG)
![capture2](https://cloud.githubusercontent.com/assets/7953349/20794073/1c3fdf6c-b7c2-11e6-95a9-7d719ecf45da.PNG)
![capture3](https://cloud.githubusercontent.com/assets/7953349/20794074/1e934f10-b7c2-11e6-9aac-9ae41cd8ea5f.PNG)

**Comment by POEDaley** [comment] 2016-12-01 12:38
As a test to help to confirm if it's a bandwidth problem or not, only connect one controller and one camera then try starting up SteamVR.  That will limit the amount of bandwidth.  Secondly, if you have a USB 2.0 port, try moving the bluetooth to that since it's definitely a different controller and root hub.

**Comment by MaVe-64** [comment] 2016-12-01 12:43
Probably the camera connection can't handle the bandwidth.  Also check with the camtest app if you have good fps.

**Comment by marcos10soares** [comment] 2016-12-01 14:37
Camera fps - ok
Test with one controller - so far seems fine (usb3.0) - this is the same port from the beginning 

Test with two controllers (usb3.0) - the second controller took a long time but eventually connected to PSMove Service. - same problem as before, lights go out in about 20 seconds

Test with two controllers (usb2.0) - both controllers connected, in steamvr one showed up as an xbox controller for some reason (the 3d design) - once in game only one detected - using 3.0 i can see the pointer of the remote in VR but with 2.0 the pointer does not show up... (wtf...)

**Comment by POEDaley** [comment] 2016-12-01 18:16
The xbox controller part I don't get at all.. but the rest does make it seem like a bandwidth issue.  Do you have a spare PCI or PCIe USB card kicking around, or one you can poach from another computer temporarily to try to see if it resolves the issue?  This would add a new USB controller to your system allowing bandwidth to be further spread out.  Even moving 1 camera and the BT adapter to that controller card should remove more than enough load on the built in controllers.

Personally, I have my 4 cameras and BT adapter spread over my USB 2.0/3.0 and 3.1 ports, along with quite a few others USB devices such as a standard webcam/headphones/kvm switch/bla bla bla.    It look a little bit of trial and error for me to find out the best combination of ports to use.

**Comment by HipsterSloth** [comment] 2016-12-01 18:35
The "xbox controller" thing is actually the place holder dual shock 4 model. This is a timing bug caused by the controller type not being set correctly when the controller state is created in the steam vr plugin. I'll try to fix this as part of my push to finalize the dualshock4 support (which basically works now that we have a kalman filter in place for it).

As for the USB bandwidth issue I would check out the tool from here and see if the bluetooth adapter is ending up on the same root hub as the cameras: 
https://r1ch.net/blog/managing-usb-bandwidth-with-usbview

**Comment by HipsterSloth** [comment] 2016-12-01 19:10
Also since this falls under the troubleshooting case this sort of discussion should generally go on the psmove service forum first: 

https://groups.google.com/forum/#!forum/psmoveservice

I'm going to close this issue for tracking purposes. If after discussion it turns out to be a reproducible that that needs a tracking issue I can re-open this.

**Closed by HipsterSloth** 2016-12-01 19:10 UTC

**Comment by marcos10soares** [comment] 2016-12-01 21:30
Ok, thanks everyone!

I will try a pcie card, and see if it resolves the issue, if not I will open this thread in troubleshooting.

Thanks again!
