### ISSUE TITLE
Test Tracking should show all connected controllers, not just the 1st controller

### ISSUE THREAD

**Issue by Sethiss** [cboulay/PSMoveService#98] opened 2016-07-05 19:37 UTC
1. One of move's are still magneta - after changing colour in Controll Calibration he switch back to Magneta.
2. Camera track only 1 rod - move a time. Second is invisible
3. Positional tracking  - Visible is only 1 rod, and is allways behind HMD.

using: 2 x move's rod, and note4

Best regards

**Comment by zelmon64** [comment] 2016-07-05 20:24
1. In normal use the first controller is always magenta, the second is cyan, third is yellow ...
2. The test tracker in the calibration tool only bothers with tracking the first controller because it's only a test. 
3. If one controller isn't showing them check that color's masks. Try re-calibrating if the controllers aren't moving properly.

**Comment by HipsterSloth** [comment] 2016-07-06 20:31
For issue 3 do you mean:
A) You only see 1 controller tracking in SteamVR 
B) You only see 1 controller tracking in the test tracking step of the config tool

If B, that is the current expected behavior in the test tool. 

Your other issues sounds like they are covered by issue #78 and issue #79.

That said, I should probably make the test tracking stage show tracking for all connected controllers. I'll rename this issue for that task.

**Comment by BogomilPetrov** [comment] 2016-07-12 01:33
I too would like for the test to include tracking of multiple controllers so I know how well the multiple controller tracking actually works. If possible even integrate rumble and button tests into that as well. I know its supposed to be a super basic tracker test but you can make it so it not only tracks the controllers but if you squeeze the triggers it does the rumble test and the PS Move button does something else. At that point it wont only be a tracker test but a full system test from tracking, controllers to functionality.Would be super useful for setting up and testing everything and how it all works together without a HMD.

**Comment by HipsterSloth** [comment] 2016-07-12 01:37
FWIW you can test rumble in the rumble test panel off of the controller settings menu (rumble gets mapped to trigger). But I agree that should all be integrated into one unified multi-controller test.

**Comment by BogomilPetrov** [comment] 2016-07-12 01:44
Oh I know it is. That's what i'm saying. Yes its useful for testing that one specific feature but having lets say one separate option that incorporates all tests into one ultimate test is the absolute best way to know if your system is working 100% without needing to plug in a HMD or use VRidge etc. Its basically going to mimic what SteamVR for example can see and work with but without needing to plug in a headset. Very useful for overall testing and tweaking. Supporting all controllers and devices at once means easier troubleshooting than just going into each thing separately. :smile: Thanks for understanding,

**Comment by HipsterSloth** [comment] 2017-03-23 06:42
I forgot to close this issue some time ago. You can now test just 1 selected controller or all controllers in the test tracking window.

**Closed by HipsterSloth** 2017-03-23 06:42 UTC
Labels: task
