### ISSUE TITLE
Cannot connect HMD

### ISSUE THREAD

**Issue by leefatty1994** [cboulay/PSMoveService#274] opened 2016-11-12 22:56 UTC
Cannot seem to connect my dk2 to the Psmoveconfigtool app.

Any help?

**Comment by HipsterSloth** [comment] 2016-11-13 23:03
Unfortunately the tutorial video is out of date so this is a bit confusing.

This is by design. The PSMoveConfigTool no longer connects to SteamVR for the purpose of aligning the HMD and the psmove tracking spaces. Instead you now are prompted in the SteamVR compositor with [this overlay](https://github.com/cboulay/PSMoveService/blob/master/src/openvr_plugin/resources/overlays/need_alignment_gesture.png?raw=true) asking you to hold the controller to your face and then press start+select. This will align the HMD and PSMove tracking spaces.

I'm going to close this issue as resolved for tracking purposes, but please feel free to post any other setup questions you have over at the PSMoveService google group: http://groups.google.com/forum/#!forum/psmoveservice

**Closed by HipsterSloth** 2016-11-13 23:03 UTC
