### ISSUE TITLE
The Tracker Pose Calibration never finds where my cameras are.

### ISSUE THREAD

**Issue by orangy57** [cboulay/PSMoveService#296] opened 2016-11-28 00:27 UTC
I've re-calibrated the camera locations with the calibration mat dozens of times, but the cameras will show up in random locations each time. Both cameras detect my controller, too.

**Comment by gb2111** [comment] 2016-11-28 07:07
Hi,
I would check color calibration if it capture only controller light.
Please go to test tracker pose and then cover light with your hand and check if all cameras turn red and fail to see the light. If not it means you need re-calibrate color.

**Comment by orangy57** [comment] 2016-11-28 23:06
I've done this, and my light Calibration is fine. My headset is tracked fine as I use VRidge, but the controllers are always calibrated wrong.

**Comment by orangy57** [comment] 2016-11-28 23:17
So I've been doing this for a bit now, and I can only move my controller when one camera is tracking the controller at a time. Is there a way I can fix this?
Also, my cameras seem to be in the correct location onscreen after redoing calibration a few times.

**Comment by HipsterSloth** [comment] 2016-12-01 19:19
Could you make a video of the controller tracking issue? I'm not sure what you mean by " I can only move my controller when one camera is tracking the controller at a time". You mean if two cameras can see the controller the controller model on screen doesn't move?

This is a troubleshooting issue I'm going to close this issue for tracking purposes, since we're trying to reserve issues for known reproducible issues (troubleshooting help is best done at https://groups.google.com/forum/#!forum/psmoveservice). That said, feel free to continue discussion here.

**Closed by HipsterSloth** 2016-12-01 19:19 UTC
