### ISSUE TITLE
PSMoveService not starting up

### ISSUE THREAD

**Issue by NyanBlade** [cboulay/PSMoveService#89] opened 2016-07-02 21:12 UTC
Hi, a new issue, i've moved the cameras around and get this error:

[2016-07-02 21:48:01.606191]: main - Starting PSMoveService
Config file name: "C:\Users#####\AppData\Roaming\PSMoveService\ControllerManagerConfig.json"
[2016-07-02 21:48:01.613182]: bluetooth_get_host_address - Found a bluetooth radio
[2016-07-02 21:48:01.616184]: bluetooth_get_host_address - Retrieved radio info
Config file name: "C:\Users#####\AppData\Roaming\PSMoveService\TrackerManagerConfig.json"
[2016-07-02 21:48:01.632209]: PS3EyeTracker::open - Opening PS3EyeTracker(USB\VID_1415&PID_2000\10\0, camera_index=0)
CLEyeGetCameraCount() found 0 devices.
libusb: error [init_device] device '\.\USB#VID_1415&PID_2000&MI_01#7&32329B5A&0&0001' is no longer connected!
ps3eye::PS3EYECam::getDevices() found 2 devices.
Config file name: "C:\Users#####\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b3_p7.json"
Config file name: "C:\Users#####\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b3_p7.json"
Config file name: "C:\Users#####\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b3_p7.json"
[2016-07-02 21:48:02.082359]: SharedMemory::initialize() - Allocating shared memory: tracker_view_0
[2016-07-02 21:48:02.099292]: EXCEPTION - PSMoveService - boost::interprocess::intermodule_singleton initialization failed
Config file name: "C:\Users#####\AppData\Roaming\PSMoveService\ControllerManagerConfig.json"
[2016-07-02 21:48:02.127310]: SharedMemory::dispose - Failed to free shared memory: tracker_view_0
[2016-07-02 21:48:02.137317]: ClientConnection::stop - Stopping client connection id 0

I have deleted .psmoveapi and PSMoveService in %appdata% and have tried the SteamVR_UninstallDriver but have no luck, any suggestions?

**Comment by zelmon64** [comment] 2016-07-02 21:23
When you say moved them, are they now in different USB ports? Have you checked which drivers are currently in use (although from `ps3eye::PS3EYECam::getDevices() found 2 devices.` it looks like that should be fine)?

**Comment by NyanBlade** [comment] 2016-07-02 21:26
They are both on libusb0 in zadig and show up fine in the camera test

**Comment by zelmon64** [comment] 2016-07-02 21:36
The line `[2016-07-02 21:48:02.099292]: EXCEPTION - PSMoveService - boost::interprocess::intermodule_singleton initialization failed` looks to be the issue but unfortunately I don't know what it means. Have you done the obvious of restarting your pc a few times? Your could try a restore point if you have a recent one (but that's a little extreme and can have side effects).

**Comment by NyanBlade** [comment] 2016-07-02 21:37
Yeah I have restarted multiple times and still get the same issue

**Comment by HipsterSloth** [comment] 2016-07-02 22:02
Woah. That's a new one on me. That has to do with shared memory I use to share video frames between PSMoveService and the config tool. I think it creates a temp file in the process and I'm wondering if it's failing to do so now for some reason. I'll need to look into that.

**Comment by NyanBlade** [comment] 2016-07-02 22:03
Thanks, is there anything I can do at the moment to fix it? Is there anyway to do a complete uninstall for a clean install?

**Comment by HipsterSloth** [comment] 2016-07-02 22:32
> Thanks, is there anything I can do at the moment to fix it? Is there anyway to do a complete uninstall for a clean install?

There's not really an ''uninstall" because nothing really get's installed. That said I just did a bit of googling for that exception and I found this:

From [here](http://forum.vcmi.eu/printview.php?t=1075&start=0&sid=61d696c69e0efe3858cee231cb2573d2):
"So as far as I get from internet problem may occur when boost::interprocess failed to get temporary directory on Windows as it's use following registry key by default: 
Code:
SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders\Common AppData

It's may occur when user modify registry with tools like CCleaner, but can be fixed by system reboot. It's should be possible to bypass that problem by setting "BOOST_INTERPROCESS_SHARED_DIR_PATH" so boost store shared memory in some other directory on Windows."

I opened regedit and found the "SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders\Common AppData" registry key. It pointed at `C:\ProgramData`. I looked in there and there was the following folder `C:\ProgramData\boost_interprocess\1466482908` containing a `tracker_view_0` and `tracker_view_1` files. 

See if that registry key exists on your machine. If it does, go to the folder it specifies. If you're running win10 it almost certainly is also `C:\ProgramData`. Then if you have a `C:\ProgramData\boost_interprocess` folder, delete the files in there. My bet is the interprocess state in there is borked and deleting them will create new ones with valid state.

**Comment by NyanBlade** [comment] 2016-07-02 22:54
Hey, thanks for that. Deleting the folder in boost_interprocess and rebooting fixed the issue :)

**Comment by NyanBlade** [comment] 2016-07-02 23:32
The camera feeds are showing mirrored in psmoveconfigtool and the move controllers are facing backwards and moving the wrong way, is there a way to fix this?

**Comment by HipsterSloth** [comment] 2016-07-03 02:13
That's wierd. Are you still using the libusb driver? I always flip the camera image I get from the camera driver so that it doesn't appear flipped. If you were using the cleye driver maybe it has some setting for mirroring the image?

**Comment by NyanBlade** [comment] 2016-07-03 17:38
Yeah i'm using the libusb driver and it's the right way round in test_camera.

**Comment by HipsterSloth** [comment] 2016-07-03 21:47
This probably won't fix the camera flip issue you are seeing, but just in case it does I have a new experimental release out that helps address camera perf issues. Would you mind giving this a try: https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha4.3.

**Comment by NyanBlade** [comment] 2016-07-03 21:51
Just tried the new release, the camera is still mirrored in psmoveconfigtool but fine in test_camera

**Comment by HipsterSloth** [comment] 2016-07-03 22:05
So I just remembered something. The camera is supposed to be flipped in the test_camera tool. The test camera tool is showing the raw camera image we get from the psmove (which is naturally flipped around). When the service is running it flips the image the way you would expect it to. 

So if you you are seeing strange tracking behavior have you:
1) Run the camera pose estimation tool yet?
2) Run the magnetometer calibration on the controllers yet?

**Comment by zelmon64** [comment] 2016-07-03 22:08
@HipsterSloth I replicated the green issue by using two adjacent usb ports and I can confirm that alpha4.3 work perfectly from what I can tell (but currently limited to two).

@NyanBlade did you see my question in #91? Since you use an OR CV1, I wanted to know whether SteamVR automatically starts when you run PSMoveConfigTool?

**Comment by NyanBlade** [comment] 2016-07-03 22:09
The test_camera tool is showing it the right way round and the service is showing it the wrong way round. The USB performance seems to be better as I don't get the green feed when I add another device. I saw #91 and SteamVR doesn't start automatically on Rift CV1.

**Comment by HipsterSloth** [comment] 2016-07-03 22:21
Sorry I should have just posted pictures because what is "right" and "wrong" varies depending on what you are trying to do with the camera. We want to flip the image in the service so moving your hand to the left makes is go to the left on screen and moving your hand to the right makes go to the right on the screen. 

Point being, if you write on a piece of paper and hold it in front of the test_tool this is what you should see:
![test_camera](https://cloud.githubusercontent.com/assets/16793853/16547905/8466aef2-4131-11e6-9fce-76a34b031c6b.jpg)

And if you then launch the config tool and look at the tracker feed this is what you should see:
![configtool](https://cloud.githubusercontent.com/assets/16793853/16547907/9c95850c-4131-11e6-87fd-e2e98fc90df4.jpg)

If that is the case for you then the camera feeds are correct. Any tracking issue are probably due to need to run the tracker pose estimation again. I'd recommend using the "mat calibration method" for best results.

**Comment by NyanBlade** [comment] 2016-07-03 22:38
@HipsterSloth It's the right way round then :) 

I will try calibrating it again later but at the moment I am having trouble using the move controllers as they turn off within a minute and don't go to a solid red led so I assume it's not being charged. Do you know how to charge them? I have left them plugged in to my computer since yesterday. They have the blinking light showing charging for a few minutes then the light turns off.

**Comment by HipsterSloth** [comment] 2016-07-03 22:44
I've heard that sometimes you have to let their battery fully drain and then try and charge them. It's also possible that the batteries aren't holding a charge anymore. Are these new or used psmoves? One used pair I bought need to have it's battery replaced.

**Comment by NyanBlade** [comment] 2016-07-03 22:47
They are old controllers I bought when they first were released but hardly used them since and not for the last few years since I got rid of my ps3. How can I check if the batteries are worn out?

**Comment by HipsterSloth** [comment] 2016-07-03 22:51
The only trick I've heard is the drain overnight an recharge trick. Beyond that I'm not sure how else to easily test them. If that doesn't work you might consider picking up some replacement batteries from Amazon:
https://www.amazon.com/Battery-PlayStation-Motion-Controller-CECH-ZCM1E/dp/B002MQ2OUO

**Comment by zelmon64** [comment] 2016-07-03 22:51
@NyanBlade For best charging I'd recommend one of the charging station. Whether they charge can depend on what driver you pc loads (hence why phone chargers don't work).

**Comment by cboulay** [comment] 2016-07-04 01:37
I read on reddit that someone had to disassemble their controller to hotwire a 5V source directly to the battery because the USB chip (or something?) was preventing the current from reaching the battery, but after he did that then it could be charged normally (after reassemble). I think buying a replacement battery sounds easier if you happen to be somewhere you can get one.

**Comment by NyanBlade** [comment] 2016-07-04 13:38
I have managed to charge them and they work now, I have two cameras in opposite corners of the room and the controllers move in the right directions but jump all over the place, is that normal?

**Comment by cboulay** [comment] 2016-07-04 15:00
The tracking volume of the PSEye is MUCH smaller than that of the Vive, and smaller than the Rift's constellation too. I think it's even slightly smaller than the DK2's camera. This is especially true in the depth-direction. Depending on how big your room is, having the cameras in opposite corners means that they are pretty far from the controller with very few pixels capturing the bulb, leading to inaccurate tracking. You're not going to get Vive-like tracking with this system.

The cameras should be close to your workspace, and your workspace should be small. If the cameras have to be far from your workspace then you can change them over to the red-dot lens setting. This has a narrower FOV but that means more pixels-per-cm at a distance. If you do this, you'll have to change a setting in the config tool and redo all your calibrations.

The jumping around will also be a lot better after I get the sensor fusion Kalman filter working. First I'm working on a C99 API. I'm actually working on that today without my kids around so I may actually make some progress!

**Comment by HipsterSloth** [comment] 2016-07-06 18:01
So it sounds like the original issue is solved here? I'm going to mark the issue as closed for tracking, but anyone is welcome to continue commenting in this thread.

**Closed by HipsterSloth** 2016-07-06 18:01 UTC
